export * from './attribute';
export * from './fragment';
export * from './func';
export * from './precision';
export * from './sampler';
export * from './sampler2D';
export * from './sampler2DArray';
export * from './depthSampler';
export * from './uniform';
export * from './uniformBlock';
export * from './varying';
// 导出 builtin 类型和工具函数
export { acos } from './builtin/acos';
export { atan } from './builtin/atan';
export { Builtin } from './builtin/builtin';
export * from './builtin/builtins';
export { clamp } from './builtin/clamp';
export { fragColor } from './builtin/fragColor';
export { cos } from './builtin/cos';
export { dot } from './builtin/dot';
export { exp } from './builtin/exp';
export { if_ } from './builtin/if_';
export { let_ } from './builtin/let';
export { max } from './builtin/max';
export { mix } from './builtin/mix';
export { normalize } from './builtin/normalize';
export { pow } from './builtin/pow';
export { return_ } from './builtin/return';
export { select } from './builtin/select';
export { sin } from './builtin/sin';
export { smoothstep } from './builtin/smoothstep';
export { sqrt } from './builtin/sqrt';
export { step } from './builtin/step';
export { texture } from './builtin/texture';
export { texture2D } from './builtin/texture2D';
export { var_ } from './builtin/var';

// 导出向量类型
export { Bool } from './builtin/types/bool';
export { Float } from './builtin/types/float';
export { UInt } from './builtin/types/uint';
export { Vec2 } from './builtin/types/vec2';
export { Vec4 } from './builtin/types/vec4';
// 导出向量构造函数
export { bool } from './builtin/types/bool';
export { float } from './builtin/types/float';
export { int } from './builtin/types/int';
export { ivec2 } from './builtin/types/ivec2';
export { ivec3 } from './builtin/types/ivec3';
export { ivec4 } from './builtin/types/ivec4';
export { mat4 } from './builtin/types/mat4';
export { mat4x3 } from './builtin/types/mat4x3';
export { uint } from './builtin/types/uint';
export { uvec2 } from './builtin/types/uvec2';
export { uvec3 } from './builtin/types/uvec3';
export { uvec4 } from './builtin/types/uvec4';
export { vec2 } from './builtin/types/vec2';
export { vec3 } from './builtin/types/vec3';
export { vec4 } from './builtin/types/vec4';
export * from './vertex';

